### ISSUE TITLE
onRequestDelete still in NPM version

### ISSUE THREAD

**Issue by natenrb9** [rodrigonehring/material-input-chips#7]
It looks like wherever NPM install is pulling from, it still has the onRequestDelete in the code.

I pulled the newest version and it says it is 1.4.1, and still throwing the error: Warning: Unknown event handler property `onRequestDelete`.

I also directly searched the code in my node_modules folder and it was `onRequestDelete` everywhere.

**Comment by rodrigonehring** [comment]
Hi @natenrb9, what version of material ui you are using?

**Comment by natenrb9** [comment]
"material-ui": "^1.0.0-beta.33"

I don't think it has to do with that though, when I look in your code on github it has onDelete (correct one), but when I look in the code pulled from NPM it has onRequestDelete.

Ah, looks like the NPM version is pulling from here: https://registry.npmjs.org/material-input-chips/-/material-input-chips-1.4.1.tgz. I think you just need to update that one.

I am also getting an error with the keys of the chips not being defined correctly from the field.value...I'm hoping this gets resolved with the updated version as well.

**Comment by rodrigonehring** [comment]
I create a new version (1.4.2), published to npm, then i downloaded and opened node_modules folder to inspect, looks fixed now.

**Comment by natenrb9** [comment]
Oh wow, that fixed all of my issues! Looks like the older version on NPM had a lot of bugs you had resolved in this new version. Thanks for the fast replies, and also building/supporting this module!
