### ISSUE TITLE
Pass props to Input?

### ISSUE THREAD

**Issue by natenrb9** [rodrigonehring/material-input-chips#8]
Maybe this is a feature request, but I don't see a way to easily pass props to the Input. Most important I would say are:

-id
-name
-placeholder

Is there a way to do this, or would this be a feature request?

**Comment by rodrigonehring** [comment]
I created and publish a new version with inputProps.

If you pass a placeholder in this object, label will be always shrinked.

I fixed some things and builded a new version of styleguidist, with a new example of inputProps.

**Comment by natenrb9** [comment]
Works perfect!! Thanks!
